### ISSUE TITLE
Enhance information status

### ISSUE THREAD

**Issue by unicodeveloper** [ibonly/youlearn#10]
If I uploaded a video and I am logged in, it should rather denote "Uploaded by: You" rather than my username.

<img width="709" alt="screen shot 2016-01-10 at 6 37 51 am" src="https://cloud.githubusercontent.com/assets/2946769/12220169/ba957e4c-b764-11e5-80a3-686ef4e44afa.png">

**Comment by ibonly** [comment]
Okay.

**Comment by ibonly** [comment]
FIXED!!!
